# Each instruction in this file generates a new layer that gets pushed to your local image cache

# Lines preceeded by # are regarded as comments and ignored

# The line below states we will base our new image on the Latest Official Ubuntu
FROM loumalouomega/kratos4debug:KratosTest

# Identify the maintainer of an image
LABEL maintainer="vicente.mataix@polytechnique.edu"

# Installing code server
USER root
ENV DEBIAN_FRONTEND=noninteractive
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN apt-get -y clean
RUN rm -rf /var/lib/apt/lists/*
ENV USER "Kratos"
USER ${USER}

# Launch code server
CMD ["code-server","--auth=none"]
