name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
    - 'docker/**'
    - '.github/**'

  schedule:
    - cron:  '0 1 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build without VSCode
      shell: bash
      run: |
        docker login -u=${{ secrets.DOCKERHUB_USER }} -p=${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -f ./docker/Dockerfile -t ${{ secrets.DOCKERHUB_USER }}/kratos4debug:KratosTest .
        docker container prune
        docker images
        docker push ${{ secrets.DOCKERHUB_USER }}/kratos4debug:KratosTest
    - name: Build with VSCode
      shell: bash
      run: |
        docker login -u=${{ secrets.DOCKERHUB_USER }} -p=${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -f ./docker/Dockerfile_with_VSCODE -t ${{ secrets.DOCKERHUB_USER }}/kratos4debug:KratosTestVSCode .
        docker container prune
        docker images
        docker push ${{ secrets.DOCKERHUB_USER }}/kratos4debug:KratosTestVSCode
