name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
    - 'Dockerfile'
    - '.github/**'

  schedule:
    - cron:  '0 1 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: |
        docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASSWORD"
        docker build -f ./Dockerfile -t kratos_test .
        docker container prune
        docker images
        docker push
